### ISSUE TITLE
When a tar decompress fails, there is a huge amount of output

### ISSUE THREAD

**Issue by maximilien** [cloudfoundry/bosh-utils#12]
When a decompress fails, it will spit out all the files it tried to decompress which will produce huge output.

This line should be changed to not run in verbose mode.

https://github.com/cloudfoundry/bosh-utils/blob/7bc7ab327a6b95a05de60840d207c778b7e9bdb4/fileutil/tarball_compressor.go#L52

cc @zankich

**Comment by cppforlife** [comment]
@maximilien fixed on master.
