### ISSUE TITLE
Support to customize logTag of bosh-utils.

### ISSUE THREAD

**Issue by edwardstudy** [cloudfoundry/bosh-utils#30]
When using bosh-utils' logger, we can get some logger format like that: `[logTag] logFlag log massage`. So we can customize logTag. And we want to modify bosh-utils' logTag, such as `retrystrategy`, `fileutil`. It can make the log format more trim when be applied.
Like retrystrategy's [code](https://github.com/cloudfoundry/bosh-utils/blob/master/retrystrategy/timeout_retry_strategy.go#L36) show, We can not modify the private property `logTag` currently.

So could you think about to customize logTag of bosh-utils.?

**Comment by dpb587-pivotal** [comment]
Hi - do you have a specific struct you are wanting to customize the log tag for? For example, I wouldn't expect the linked retryable code to need customization since it is fairly generic. But, perhaps some other components may benefit for the configurability.
