### ISSUE TITLE
httpclient.SOCKS5DialFuncFromEnvironment should return "BOSH_ALL_PROXY" parsing errors

### ISSUE THREAD

**Issue by ChunyiLyu** [cloudfoundry/bosh-utils#44]
Hi bosh team, 

When investigating how to use BOSH_ALL_PROXY in https://github.com/cloudfoundry/bosh-cli/issues/432, we have found that when the BOSH_ALL_PROXY is misconfigured, there is no helpful error message returned from the bosh cli, even when setting `BOSH_LOG_LEVEL=debug`. We think that when BOSH_ALL_PROXY is set, the value of BOSH_ALL_PROXY should be valid, and any parsing error should be shown to the operator for easier debugging.  When BOSH_ALL_RPOXY is misconfigured, instead of returning the original dialer in [httpclient.SOCKS5DialFuncFromEnvironment](https://github.com/cloudfoundry/bosh-utils/blob/9a2bb19b92823974d44fcf1e84e326c4d4a63061/httpclient/socksify.go#L36), we can return a function that returns the parsing error.

Cheers,
Chunyi && @jamesjoshuahill

**Comment by jamesjoshuahill** [comment]
Resolved by https://github.com/cloudfoundry/bosh-utils/pull/45
