### ISSUE TITLE
Need to redact sensitive data in log output

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-utils#69]
Currently, we are using `bosh-utils` to output messages in cpi log, for security reason, we need to redact sensitive data, like password and keys, in cpi log. We are wondering if bosh-utils has any plan to add such functionality, we have some experimental code like below, we know there should get the code more flexible to support to specify some keywords to redact. Any ideas? thanks.

```
func redact(bs []byte) []byte {
	s := string(bs)

	hiddenStr1 := "\"password\":\"<redact>\""
	r1 := regexp.MustCompile(`"password":"[^"]*"`)
	s1 := r1.ReplaceAllString(s, hiddenStr1)

	hiddenStr2 := "\"api_key\":\"<redact>\""
	r2 := regexp.MustCompile(`"api_key":"[^"]*"`)
	s2 := r2.ReplaceAllString(s1, hiddenStr2)

	hiddenStr3 := "//registry:<redact>"
	r3 := regexp.MustCompile(`//registry:[^@]*`)
	s3 := r3.ReplaceAllString(s2, hiddenStr3)

	hiddenStr4 := "//nats:<redact>"
	r4 := regexp.MustCompile(`//nats:[^@]*`)
	s4 := r4.ReplaceAllString(s3, hiddenStr4)

	return []byte(s4)
}
```

```
func (fs *osFileSystem) ReadFileWithRedact(path string) (content []byte, err error) {
	fs.logger.Debug(fs.logTag, "Reading file %s", path)

	file, err := fs.OpenFile(path, os.O_RDONLY, 0)
	if err != nil {
		err = bosherr.WrapErrorf(err, "Opening file %s", path)
		return
	}

	defer file.Close()

	content, err = ioutil.ReadAll(file)
	if err != nil {
		err = bosherr.WrapErrorf(err, "Reading file content %s", path)
		return
	}

	fs.logger.DebugWithDetails(fs.logTag, "Read content", redact(content))
	return
}
```

/cc @gu-bin

**Comment by mattcui** [comment]
@dpb587-pivotal Do you have any ideas/comments? Thanks.

**Comment by christarazi** [comment]
@mattcui There are currently no plans for this. If you'd like to open a PR, we'd be happy to take a look.

**Comment by gu-bin** [comment]
@christarazi This is the PR https://github.com/cloudfoundry/bosh-utils/pull/71
I don't know how to write the unit test as it only affects the debug log output. Please advise how to do that. Thanks.
