### ISSUE TITLE
Should bosh-utils respect $NO_PROXY instead of $no_proxy?

### ISSUE THREAD

**Issue by chenweienn** [cloudfoundry/bosh-utils#78]
From BOSH [doc](https://bosh.io/docs/cli-global-flags/#http-proxy), I think `NO_PROXY` should be respected instead of `no_proxy`.

In this bosh-utils [code](https://github.com/cloudfoundry/bosh-utils/blob/master/httpclient/socksify.go#L103-L106), `$no_proxy` is respected.
```
	noProxy := os.Getenv("no_proxy")
	if len(noProxy) != 0 {
		perHost.AddFromString(noProxy)
	}
```

It could cause problem in the following use case.

- Foundation-A to be backed up:
   - BOSH, TKGI, ...
- Foundation-B running bbr-pcf-pipeline-tasks:
   - BOSH, TKGI, ...
   - concourse is installed via Helm chart on TKGI, in order to run [bbr-pcf-pipeline-tasks](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks)

The BOSH directors in both foundations use identical private subnet CIDR: `172.16.25.0/24` and occupies identical private IP: `172.16.25.14`.

The bbr-backup-director task running in foundation-B uses a CLI tool [bbr](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore) to backup foundation-A BOSH director. In order to connect with foundation-A BOSH director, bbr uses bosh-utils/httpclient to [build dialFunc](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/blob/017c6807eb275ca630e4d289957ee88978367ee3/ssh/connection.go#L145).
bosh-utils/httpclient respects `$BOSH_ALL_PROXY` and `$no_proxy`.

However, the concourse helm chart in foundation-B is installed with `$no_proxy` containing bosh director private CIDR `172.16.25.0/24`. As a consequence, bbr (bosh-utils/httpclient) connects with local BOSH director in foundation-B and thus hit an SSH error due to using ssh key meant for foundation-A BOSH director.

We workaround the issue by removing BOSH director private CIDR from `$no_proxy`.

**Question:**
Should we replace no_proxy with NO_PROXY in this bosh-utils [code](https://github.com/cloudfoundry/bosh-utils/blob/master/httpclient/socksify.go#L103) ?

**Comment by mrosecrance** [comment]
Do you have more information on why $no_proxy is being set and why it includes the director subnet? 

A quick look at [Golangs usage](https://pkg.go.dev/golang.org/x/net/http/httpproxy?utm_source=godoc#Config) shows it will honor both no_proxy and NO_PROXY which indicates to me that the "correct" answer might be to toggle on both rather than just one.

**Comment by chenweienn** [comment]
> Do you have more information on why $no_proxy is being set and why it includes the director subnet?

The bbr-backup-director task running in foundation-B is managed by concourse. When deploying concourse in foundation-B, `$http_proxy`, `$https_proxy` and `$no_proxy` are [set](https://github.com/concourse/concourse-chart/blob/master/values.yaml#L1524-L1534). `$https_proxy` contains the enterprise proxy of customer. All egress traffic to Internet from the foundation-B should go through `$https_proxy`. The purpose of including director CIDR in `$no_proxy` is because from the perspective of foundation-B on its own, there is no need to use `$https_proxy` for reaching the local bosh director in foundation-B.

It is common that a customer operates multiple foundations (BOSH, TAS, TKGI, etc., which are configured with identical private CIDRs) and run [bbr-pcf-pipeline-tasks](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks) in one foundation to backup/restore all the other foundations.

In the aforementioned use case, the bbr-backup-director task running in foundation-B needs to connect with the foundation-A bosh director which is running in another private CIDR not directly reachable from foundation-B. To achieve this, the bbr task takes the [tunneling method](https://bosh.io/docs/cli-tunnel/) described in BOSH doc. In particular, it [sets up an SSH tunnel](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/master/scripts/export-director-metadata#L45-L48) into `$BOSH_ALL_PROXY` and allow [toggling](https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks/blob/master/scripts/export-director-metadata#L54-L58) `$NO_PROXY` for connecting with either local or remote bosh director.

- when `$NO_PROXY` is set including the bosh director IP, the bbr task intends to connect with it directly, bypassing `$BOSH_ALL_PROXY`;
- when `$NO_PROXY` is not set, the bbr task will use `$BOSH_ALL_PROXY` assuming the targeted director is a remote director not locally reachable.

In summary, the lowercase versions are set up at concourse level ant are scoped to impact all tasks running by concourse including the bbr-backup-director task. The uppercase versions are used by the bbr-backup-director task, based on the following bosh doc.

Per bosh [doc](https://bosh.io/docs/cli-global-flags/#http-proxy), the BOSH CLI follows golang practice to respect `$HTTP_PROXY`, `$HTTPS_PROXY` and `$NO_PROXY`, without mentioning of lowercase versions thereof. Although per golang [code](https://github.com/golang/net/blob/064579744ee0/http/httpproxy/proxy.go#L90-L106) the lowercase versions are also supported but with lower precedence.

Per my testing, bosh-utils does not respect `$NO_PROXY` but respect only `$no_proxy`. My testing cases:

1. setup a tunnel to director via export `$BOSH_ALL_PROXY`, and
2. `export no_proxy=<director_ip>`, and
3. `export NO_PROXY` with values as follows:
    - `NO_PROXY=<director_ip>`: the connection does NOT go through the tunnel
    - `NO_PROXY=<some random ip>`: the connection does NOT go through the tunnel
    - `unset NO_PROXY`: the connection does NOT go through the tunnel
4.  `unset no_proxy` and `export NO_PROXY=<director_ip>`: the connection goes through the tunnel

The testing result is inconsistent with the BOSH [doc](https://bosh.io/docs/cli-global-flags/#http-proxy). I think it would be better if we let bosh-utils support only uppercase versions. I understand there might be some historical stories or customer issues which result into the current behavior of bosh-utils. Or I may understand the design purpose incorrectly. Please help investigate and correct me if I am wrong. Thanks.

**Comment by mrosecrance** [comment]
So to clarify, you all will be setting NO_PROXY to something so that no_proxy will not be used? Are you sure that traffic you want to go to the director will ignore the capital `NO_PROXY` but continue to respect the lower case version?

**Comment by chenweienn** [comment]
> So to clarify, you all will be setting NO_PROXY to something so that no_proxy will not be used?

Yes. If bosh-utils need to support both `NO_PROXY` and `no_proxy`, I propose `NO_PROXY` takes precedence over `no_proxy`.

> Are you sure that traffic you want to go to the director will ignore the capital `NO_PROXY` but continue to respect the lower case version?

Yes. Per my testing, bosh-utils currently does not respect `NO_PROXY` but respects only `no_proxy`.

**Comment by mrosecrance** [comment]
For the NO_PROXY bit, I was referring to concourse or the foundation or whatever it is that currently respects `no_proxy`. Will that part ignore `NO_PROXY` or will making this change just move the problem around? This seems like a situation where you want two different no proxying behavior, and we're switching around names to make that happen - which will only work if the other components ignore NO_PROXY.

**Comment by chenweienn** [comment]
> So to clarify, you all will be setting NO_PROXY to something so that no_proxy will not be used?
> For the NO_PROXY bit, I was referring to concourse or the foundation or whatever it is that currently respects no_proxy. 

Currently bbr-pcf-pipeline-tasks assumes that bosh-utils would respect NO_PROXY. I quote the comment from BBR team in [this JIRA](https://pivotal-io.atlassian.net/browse/BBR-5).
`In BBR we don’t have any strong opinions on whether bosh-utils should use “no_proxy” or “NO_PROXY”, we agree that whichever it does it should match the docs.`

For OpsMan or the foundation, usually they do not use proxy to connect with BOSH director, because they are made accessible locally in a typical installation. I cannot speak much for them with my limited experience.

> This seems like a situation where you want two different no proxying behavior

I expect a single behavior without ambiguity and also expect it to be documented in bosh [doc](https://bosh.io/docs/cli-global-flags/#http-proxy).  When other components using BOSH, they should also use NO_PROXY and no_proxy in a correct way that BOSH expects.  At this moment, BOSH doc respects uppercase versions (following the golang approach) but the underlying bosh-utils does not respect NO_PROXY. This is not consistent. Once BOSH has addressed this inconsistency, the other components (bbr in my case) should adjust their usage of NO_PROXY/no_proxy accordingly. Thanks.

**Comment by mrosecrance** [comment]
Done
