### ISSUE TITLE
`bosh create-release` fails if gnutar is default `tar` on macOS

### ISSUE THREAD

**Issue by geigerj0** [cloudfoundry/bosh-utils#86]
# Problem
The following change f79167bd43f3afc154065edc95799a464a80605f introduced the usage of `--no-mac-metadata` when creating a tarball on macOS. Usually, bsdtar is the default `tar` on macOS which has the option `--no-mac-metadata` so the tarball creation will work. 

In some cases, it can happen that gnutar is the default `tar` instead of bsdtar on macOS. One thing to note here is that gnutar doesn't have the `--no-mac-metadata` option. Another thing to note is that `bosh` CLI reuses `bosh-utils`, [see go.mod of `bosh-cli`](https://github.com/cloudfoundry/bosh-cli/blob/5e5f5691bd2d55cd38d2ee65db2deaa0fe3ec8f7/go.mod#L13). These two facts lead to the following problem: having gnutar as the default `tar` on macOS will make `bosh create-release` fail with the following error message (scroll to the very right in the bash-sample below to see `'tar: unrecognized option '--no-mac-metadata'`): 
```bash
❯ bosh create-release --force --version="123"
Building a release from directory '<redacted>/my-bosh-app':
  - Compressing staging directory:
      Shelling out to tar:
        Running command: 'tar --no-mac-metadata -czf /Users/<redacted>/.bosh/tmp/bosh-platform-disk-TarballCompressor-CompressSpecificFilesInDir2852006618 -C /Users/<redacted>/.bosh/tmp/bosh-resource-archive2997908519 .', stdout: '', stderr: 'tar: unrecognized option '--no-mac-metadata'
Try 'tar --help' or 'tar --usage' for more information.
':
```

## Example to reproduce the error on macOS when gnu-tar installed via Homebrew and set as default
```bash
# install gnutar
brew install gnu-tar

# add path to gnutar at the very beginning of $PATH so that it will be the default when calling `tar` on the command line
PATH="$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH"

# install bosh-cli version above v7.3.1 (it does `--no-mac-metadata` during `bosh create-release`)
brew install bosh-cli

# clone a bosh repo
git clone https://github.com/cloudfoundry/app-autoscaler-release.git
cd app-autoscaler-release

# create bosh release and check the error that will be returned
bosh create-release --force --version="123"
```

## Example to reproduce the error on macOS via Nix shell where gnutar is the default tar
```bash
# clone a bosh repo which has a flake.nix 
# with bosh-cli above v7.3.1 (it does `--no-mac-metadata` during `bosh create-release`) 
# and gnutar as default from Nix
git clone https://github.com/cloudfoundry/app-autoscaler-release.git
cd app-autoscaler-release

# enter Nix development shell
nix develop

# create bosh release and check the error that will be returned
bosh create-release --force --version="123"
```

**Comment by rkoster** [comment]
Personally I have worked around this by doing the following:
https://github.com/rkoster/nixpkgs/blob/master/pkgs/bosh/default.nix#L20

**Comment by geigerj0** [comment]
> Personally I have worked around this by doing the following: https://github.com/rkoster/nixpkgs/blob/master/pkgs/bosh/default.nix#L20

I like your hack to overcome this issue 🚀 😄 👍. 

Is there a reason why this problem is not fixed at the root (this repository)?

**Comment by rkoster** [comment]
It was unclear to me how widespread the combination of Nix + MacOS is among the bosh cli users. Because the issue is really Nix specific. Also, Nix users are used to having to patch upstream OSS projects to be able to adhere to Nix standards.
