### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Fydon** [cloudfoundry/bosh-utils#9]
As mentioned in [bosh-cli][1], in order for tar compress and decompress to work on Windows, a library, e.g. [`archive/tar`][4], would need to be use, as it was in the [Ruby cli][2].

[1]: https://github.com/cloudfoundry/bosh-cli/issues/53
[2]: https://github.com/cloudfoundry/bosh/issues/1292
[3]: https://golang.org/pkg/archive/tar/
[4]: https://golang.org/pkg/archive/tar/

**Comment by cppforlife** [comment]
@Fydon that makes sense.

**Comment by charlievieth** [comment]
As noted in https://github.com/cloudfoundry/bosh-utils/pull/11 please use the [BSD tar](https://github.com/cloudfoundry/bosh-agent/blob/master/integration/windows/fixtures/tar.exe) and [zlib.dll](https://github.com/cloudfoundry/bosh-agent/blob/master/integration/windows/fixtures/zlib1.dll) from [bosh-agent](https://github.com/cloudfoundry/bosh-agent).

**Comment by charlievieth** [comment]
We created a story to document tar on Windows and where to find it: [139998715](https://www.pivotaltracker.com/story/show/139998715).  Additionally, we have a [story](https://www.pivotaltracker.com/story/show/139296349) to start compiling tar for Windows and will make the binary available.
